sync with mlton/mlton master

diff --git a/bin/mlton-script b/bin/mlton-script
--- a/bin/mlton-script
+++ b/bin/mlton-script
@@ -2,34 +2,23 @@
 
 # This script calls MLton.
 
+
+LIB_REL_BIN="../lib/mlton"
+
+EXE=
+
+CC="gcc"
+
+# You may need to set 'GMP_INC_DIR' so the C compiler can find gmp.h.
+GMP_INC_DIR=
+# You may need to set 'GMP_LIB_DIR' so the C compiler can find libgmp.
+GMP_LIB_DIR=
+
+
 set -e
 
 dir=`dirname "$0"`
-lib=`cd "$dir/../lib" && pwd`
-eval `"$lib/platform"`
-gcc='gcc'
-case "$HOST_OS" in
-mingw)
-	exe='.exe'
-;;
-hpux)
-        ia64hpux="-mlp64"
-;;
-*)
-	exe=''
-;;
-esac
-mlton="$lib/mlton-compile$exe"
-
-smlnj='sml'
-if $smlnj -h >/dev/null 2>&1; then
-        smlnj_heap_suffix=`echo 'TextIO.output (TextIO.stdErr, SMLofNJ.SysInfo.getHeapSuffix ());' | $smlnj 2>&1 1> /dev/null`
-        mlton_smlnj_heap="$lib/mlton-smlnj.$smlnj_heap_suffix"
-else
-        mlton_smlnj_heap=""
-fi
-
-mlton_polyml="$lib/mlton-polyml$exe"
+lib=`cd "$dir/$LIB_REL_BIN" && pwd`
 
 declare -a rargs
 case "$1" in
@@ -49,74 +38,63 @@ case "$1" in
 esac
 
 doitMLton () {
-    exec "$mlton" @MLton ram-slop 0.5 "${rargs[@]}" -- "$@"
+    mlton_mlton="$lib/mlton-compile$EXE"
+    if [ -x "$mlton_mlton" ]; then
+        exec "$mlton_mlton" @MLton ram-slop 0.5 "${rargs[@]}" -- "$@"
+    fi
 }
 doitSMLNJ () {
-    exec "$smlnj" @SMLload="$mlton_smlnj_heap" "$@"
+    smlnj='sml'
+    if $smlnj -h >/dev/null 2>&1; then
+        smlnj_heap_suffix=`echo 'TextIO.output (TextIO.stdErr, SMLofNJ.SysInfo.getHeapSuffix ());' | $smlnj 2>&1 1> /dev/null`
+        mlton_smlnj_heap="$lib/mlton-smlnj.$smlnj_heap_suffix"
+        if [ -s "$mlton_smlnj_heap" ]; then
+            exec "$smlnj" @SMLload="$mlton_smlnj_heap" "$@"
+        fi
+    fi
 }
 doitPolyML () {
-    exec "$mlton_polyml" "$@"
+    mlton_polyml="$lib/mlton-polyml$EXE"
+    if [ -x "$mlton_polyml" ]; then
+        exec "$mlton_polyml" "$@"
+    fi
 }
 
 doit () {
-        if [ -x "$mlton" ]; then
-            doitMLton "$@"
-        elif [ -s "$mlton_smlnj_heap" ]; then
-            doitSMLNJ "$@"
-        elif [ -x "$mlton_polyml" ]; then
-            doitPolyML "$@"
-        fi
-        echo 'Unable to run MLton.  Check that lib is set properly.' >&2
-        exit 1
+    doitMLton "$@"
+    doitSMLNJ "$@"
+    doitPolyML "$@"
+    echo 'Unable to run MLton.  Check that lib is set properly.' >&2
+    exit 1
 }
 
-# For align-{functions,jumps,loops}, we use -m for now instead of
-# -f because old gcc's will barf on -f, while newer ones only warn
-# about -m.  Someday, when we think we won't run into older gcc's,
-# these should be changed to -f.
-
-# You may need to add a line with -cc-opt 'I/path/to/gmp.h' so the
-# C compiler can find gmp.h
-# You may need to add a line with -link-opt '-L/path/to/libgmp' so
-# that the linker can find libgmp.
-
-# The darwin linker complains (loudly) about non-existent library
-# search paths.
-darwinLinkOpts=''
-if [ -d '/usr/local/lib' ]; then
-        darwinLinkOpts="$darwinLinkOpts -L/usr/local/lib"
+if [ -n "$GMP_INC_DIR" ]; then
+gmpCCOpts="-cc-opt -I$GMP_INC_DIR"
 fi
-if [ -d '/opt/local/lib' ]; then
-        darwinLinkOpts="$darwinLinkOpts -L/opt/local/lib"
-fi
-if [ -d '/sw/lib' ]; then
-        darwinLinkOpts="$darwinLinkOpts -L/sw/lib"
+if [ -n "$GMP_LIB_DIR" ]; then
+gmpLinkOpts="-link-opt -L$GMP_LIB_DIR -target-link-opt netbsd -Wl,-R$GMP_LIB_DIR"
 fi
 
 doit "$lib" \
         -ar-script "$lib/static-library"                         \
-        -cc "$gcc"                                               \
+        -cc "$CC"                                                \
+        -cc-opt '-std=gnu11 -fno-common'                         \
+        -cc-opt '-O1 -fomit-frame-pointer -fno-strict-aliasing'  \
+        -cc-opt '-w'                                             \
         -cc-opt-quote "-I$lib/include"                           \
-        -cc-opt '-O1 -fno-common'                                \
-        -cc-opt '-fno-strict-aliasing -fomit-frame-pointer -w'   \
         -link-opt '-lm -lgmp'                                    \
+        $gmpCCOpts $gmpLinkOpts                                  \
         -llvm-llc-opt '-O2'                                      \
         -llvm-opt-opt '-mem2reg -O2'                             \
-        -mlb-path-map "$lib/mlb-path-map"                        \
+        -mlb-path-var 'SML_LIB $(LIB_MLTON_DIR)/sml'             \
         -target-as-opt amd64 '-m64'                              \
         -target-as-opt x86 '-m32'                                \
         -target-cc-opt alpha                                     \
                 '-mieee -mbwx -mtune=ev6 -mfp-rounding-mode=d'   \
         -target-cc-opt amd64 '-m64'                              \
-        -target-cc-opt darwin                                    \
-                '-I/usr/local/include
-                 -I/opt/local/include
-                 -I/sw/include'                                  \
-        -target-cc-opt freebsd '-I/usr/local/include'            \
-        -target-cc-opt netbsd '-I/usr/pkg/include'               \
-        -target-cc-opt openbsd '-I/usr/local/include'            \
         -target-cc-opt aix '-maix64'                             \
-        -target-cc-opt ia64 "$ia64hpux -mtune=itanium2"          \
+        -target-cc-opt ia64-hpux "-mlp64"                        \
+        -target-cc-opt ia64 "-mtune=itanium2"                    \
         -target-cc-opt sparc '-m32 -mcpu=v8 -Wa,-xarch=v8plusa'  \
         -target-cc-opt x86                                       \
                 '-m32
@@ -129,17 +107,12 @@ doit "$lib" \
         -target-link-opt amd64 '-m64'                            \
         -target-link-opt alpha                                   \
                 '-mieee -mbwx -mtune=ev6 -mfp-rounding-mode=d'   \
-        -target-link-opt darwin "$darwinLinkOpts"                \
-        -target-link-opt freebsd '-L/usr/local/lib/'             \
         -target-link-opt aix '-maix64'                           \
-        -target-link-opt ia64 "$ia64hpux"                        \
+        -target-link-opt ia64-hpux "-mlp64"                      \
         -target-link-opt linux '-Wl,-znoexecstack'               \
         -target-link-opt mingw                                   \
                 '-lws2_32 -lkernel32 -lpsapi -lnetapi32 -lwinmm' \
         -target-link-opt mingw '-Wl,--enable-stdcall-fixup'      \
-        -target-link-opt netbsd                                  \
-                '-Wl,-R/usr/pkg/lib -L/usr/pkg/lib/'             \
-        -target-link-opt openbsd '-L/usr/local/lib/'             \
         -target-link-opt solaris '-lnsl -lsocket -lrt'           \
         -target-link-opt x86 '-m32'                              \
         -profile-exclude '\$\(SML_LIB\)'                         \
