knownfaillist

diff --git a/bin/regression b/bin/regression
--- a/bin/regression
+++ b/bin/regression
@@ -8,89 +8,57 @@
 name=`basename "$0"`
 
 usage () {
-        echo >&2 "usage: $name [-cross target] [-resume test] [-run-only target] [-short] [-test-reg reg] [mlton flags ...]"
-        exit 1
+  echo >&2 "usage: $name [-fail] [-short] [-test-reg reg] [mlton flags ...]"
+  exit 1
 }
 
-cross='false'
 fail='false'
-resume='true'
-resumeTest='nil'
-runOnly='false'
 short='false'
 testReg='false'
+exitFail=false
+passed=0
+failed=0
 declare -a testRegs
 declare -a flags
 declare -a extraFlags
 flags[${#flags[@]}]="-type-check"
 flags[${#flags[@]}]="true"
 while [ "$#" -gt 0 ]; do
-        case "$1" in
-        -cross)
-                cross='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                crossTarget="$1"
-                shift
-                ;;
-        -fail)
-                fail='true'
-                shift
-                ;;
-        -resume)
-                resume='false'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                resumeTest="$1"
-                shift
-                ;;
-        -run-only)
-                runOnly='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                crossTarget="$1"
-                shift
-                ;;
-        -short)
-                short='true'
-                shift
-                ;;
-        -test-reg)
-                testReg='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                testRegs[${#testRegs[@]}]="$1"
-                shift
-                ;;
-        *)
-                flags[${#flags[@]}]="$1"
-		shift
-                ;;
-        esac
+  case "$1" in
+  -fail)
+          fail='true'
+          shift
+          ;;
+  -short)
+          short='true'
+          shift
+          ;;
+  -test-reg)
+          testReg='true'
+          shift
+          if [ "$#" = 0 ]; then
+                  usage
+          fi
+          testRegs[${#testRegs[@]}]="$1"
+          shift
+          ;;
+  *)
+          flags[${#flags[@]}]="$1"
+          shift
+          ;;
+  esac
 done
+
 
 dir=`dirname "$0"`
 src=`cd "$dir/.." && pwd`
 bin="$src/build/bin"
-lib="$src/build/lib"
+lib="$src/build/lib/mlton"
 mlton="$bin/mlton"
+
 flags[${#flags[@]}]="-codegen"
 flags[${#flags[@]}]="c"
 
-if $cross; then
-	flags[${#flags[@]}]="-target"
-	flags[${#flags[@]}]="$crossTarget"
-	flags[${#flags[@]}]="-stop"
-	flags[${#flags[@]}]="g"
-fi
 cont='callcc.sml callcc2.sml callcc3.sml once.sml'
 flatArray='finalize.sml flat-array.sml flat-array.2.sml'
 intInf='conv.sml conv2.sml fixed-integer.sml harmonic.sml int-inf.*.sml slow.sml slower.sml smith-normal-form.sml'
@@ -98,16 +66,40 @@ signal='finalize.sml signals.sml signals2.sml signals3.sml signals4.sml suspend.
 thread='thread0.sml thread1.sml thread2.sml mutex.sml prodcons.sml same-fringe.sml timeout.sml'
 world='world1.sml world2.sml world3.sml world4.sml world5.sml world6.sml'
 tmp=/tmp/z.regression.$$
-PATH="$bin:$src/bin/.:$PATH"
+PATH="$bin:$PATH"
 
-eval `"$lib/platform"`
+# knownfaillist tests that are known to fail (will still run but exit cleanly)
+declare -A knownfaillisted
+if [ -a  $src/regression/knownfaillist ] ; then
+  while read f ; do
+    echo "knownfaillisting $f..."
+    knownfaillisted["$f"]=1
+  done <$src/regression/knownfaillist
+fi
+
+isKnownfaillisted () {
+  local f=$1
+  if [[ ${knownfaillisted["$f"]} ]] ; then
+    echo 1
+  else
+    echo 0
+  fi
+}
 
 compFail () {
         echo "compilation of $f failed with ${flags[*]}"
 }
 
-"$mlton" -verbose 1 || echo 'no mlton present'
+"$mlton" -verbose 1 || (echo 'no mlton present' && exitFail=true)
 echo "flags = ${flags[*]}"
+
+TARGET_ARCH=`"$mlton" -show path-map | sed -n 's/TARGET_ARCH \(.*\)/\1/p'`
+TARGET_OS=`"$mlton" -show path-map | sed -n 's/TARGET_OS \(.*\)/\1/p'`
+OBJPTR_REP=`"$mlton" -show path-map | sed -n 's/OBJPTR_REP \(.*\)/\1/p'`
+ALIGN=`echo "${flags[@]}" | sed -n 's/.*-align \(.\).*/\1/p'`
+if [ -z "$ALIGN" ]; then
+    ALIGN=`"$mlton" -z 2>&1 | sed -n 's/.*-align {\(.\).*/\1/p'`
+fi
 
 cd "$src/regression"
 
@@ -115,31 +107,31 @@ if $fail; then
         for f in fail/*.sml; do
                 echo "testing $f"
                 ( "$mlton" "${flags[@]}" -stop tc "$f" >/dev/null 2>&1 &&
-                        echo "compilation of $f should have failed but did not" ) ||
+                        echo "compilation of $f should have failed but did not" && ignore=$(isKnownfaillisted $f) && if [ "$ignore" -eq 0 ] ; then exitFail=true ; fi ) ||
                         true
         done
-        exit 0
+
+        if [ "$exitFail" = true ] ; then
+          exit 1
+        else
+          exit 0
+        fi
 fi
 
 forMinGW='false'
-if [ `host-os` = mingw ]; then
+if [ $TARGET_OS = mingw ]; then
 	forMinGW='true'
 fi
-case $crossTarget in
-*mingw)
-	forMinGW='true'
-;;
-esac
 
 for f in *.sml; do
         f=`basename "$f" .sml`
- 	if ! ($resume); then
-                if [ "$f" == "$resumeTest" ]; then
-                        resume='true'
-                else
-                        continue
-                fi
+        ignore=$(isKnownfaillisted $f)
+        if [ "$ignore" -eq 1 ] ; then
+            echo "skipping $f"
+            failed=$((failed+1))
+            continue
         fi
+
         if ($testReg); then
                 skip='true'
                 for (( i = 0 ; $i < ${#testRegs[@]} ; i++ )); do
@@ -151,7 +143,7 @@ for f in *.sml; do
                         continue
                 fi
         fi
-        case `host-os` in
+        case $TARGET_OS in
         cygwin)
                 case "$f" in
                 textio.2)
@@ -179,7 +171,7 @@ for f in *.sml; do
         serialize)
                 continue
         ;;
-	esac
+	      esac
         echo "testing $f"
         unset extraFlags
         case "$f" in
@@ -187,115 +179,125 @@ for f in *.sml; do
                 extraFlags[${#extraFlags[@]}]="-const"
                 extraFlags[${#extraFlags[@]}]="Exn.keepHistory true"
         ;;
+        gc-collect2)
+                extraFlags[${#extraFlags[@]}]="-runtime"
+                extraFlags[${#extraFlags[@]}]="mark-compact-ratio 1.001 copy-ratio 1.001 live-ratio 1.001"
+        ;;
+        world*)
+                extraFlags[${#extraFlags[@]}]="-link-opt"
+                extraFlags[${#extraFlags[@]}]="-no-pie"
+        ;;
         esac
-	if (! $runOnly); then
-                mlb="$f.mlb"
-                echo "\$(SML_LIB)/basis/basis.mlb
-                        \$(SML_LIB)/basis/mlton.mlb
-                        \$(SML_LIB)/basis/sml-nj.mlb
-                        ann 
-                                \"allowFFI true\"
-                                \"allowOverload true\"
-                                \"nonexhaustiveMatch ignore\"
-                                \"redundantMatch ignore\"
-                        in $f.sml 
-                        end" >"$mlb"
-                "$mlton" "${flags[@]}" "${extraFlags[@]}" -output "$f" "$mlb"
-                if [ "$?" -ne '0' ] || ((! $cross) && [ ! -x "$f" ]); then
-                        compFail "$f"
-                fi
-                rm "$mlb"
-	else
-                case "$crossTarget" in
-                *mingw)
-                        libs='-lws2_32 -lkernel32 -lpsapi -lnetapi32'
-                ;;
-                *solaris)
-                        libs='-lnsl -lsocket -lrt'
-                ;;
-                *)
-                        libs=''
-                ;;
-                esac
-                libs="-lmlton -lgmp $libs -lgdtoa -lm"
-                # Must use $f.[0-9].[csS], not $f.*.[csS], because the
-                # latter will include other files, e.g. for finalize,
-                # it will also include finalize.2. This happens only 
-		# when running cross regressions, which builds all the
-		# C files and saves them in this directory.
-		files="$f.[0-9].[csS]"
-		if [ 0 -ne `ls $f.[0-9][0-9].[csS] 2>/dev/null | wc -l` ]; then
-			files="$files $f.[0-9][0-9].[csS]"
-		fi
-                gcc -o "$f" -w -O1                              \
-                        -I "/usr/local/include" \
-                        -I "../build/lib/include"               \
-			-I "../build/lib/targets/$crossTarget/include"  \
-                        -L"../build/lib/targets/$crossTarget"           \
-                        -L/usr/pkg/lib                          \
-                        -L/usr/local/lib                        \
-                        $files $libs
-	fi
-        if [ ! -r "$f".nonterm -a $cross = 'false' -a -x "$f" ]; then
+
+        mlb="$f.mlb"
+        echo "\$(SML_LIB)/basis/basis.mlb
+                \$(SML_LIB)/basis/mlton.mlb
+                \$(SML_LIB)/basis/sml-nj.mlb
+                ann 
+                        \"allowFFI true\"
+                        \"allowOverload true\"
+                        \"nonexhaustiveMatch ignore\"
+                        \"redundantMatch ignore\"
+                in $f.sml 
+                end" >"$mlb"
+        "$mlton" "${flags[@]}" "${extraFlags[@]}" -output "$f" "$mlb"
+        if [ "$?" -ne '0' ] || [ ! -x "$f" ]; then
+                compFail "$f"
+                failed=$((failed+1))
+                exitFail=true
+        fi
+        rm "$mlb"
+
+        if [ ! -r "$f".nonterm -a -x "$f" ]; then
                 nonZeroMsg='Nonzero exit status.'
-		if $forMinGW; then
-                       nonZeroMsg="$nonZeroMsg"'\r'
-		fi
+                if $forMinGW; then
+                        nonZeroMsg="$nonZeroMsg"'\r'
+                fi
                 ( "./$f" || echo -e "$nonZeroMsg" ) >$tmp 2>&1 
                 if [ -r "$f.ok" ]; then
-                        compare="$f.$HOST_ARCH-$HOST_OS.ok"
-                        if [ ! -r $compare ]; then
-                                compare="$f.ok"
-                        fi
-			if $forMinGW; then
+                        compare="$f.ok"
+                        for x in "$OBJPTR_REP" "${OBJPTR_REP}a$ALIGN" "$TARGET_OS" "$TARGET_ARCH" "$TARGET_ARCH-$TARGET_OS"; do
+                                if [ -r "$f.$x.ok" ]; then
+                                        compare="$f.$x.ok"
+                                fi
+                        done
+                        if $forMinGW; then
                                 newcompare="$f.sed.ok"
                                 sed $'s/$/\r/' <"$compare" > "$newcompare"
                                 compare="$newcompare"
-			fi
+                        fi
                         if ! diff "$compare" "$tmp"; then
                                 echo "$f: difference with ${flags[*]} ${extraFlags[*]}"
+                                ignore=$(isKnownfaillisted $f)
+                                if [ "$ignore" -eq 0 ] ; then
+                                    failed=$((failed+1))
+                                    exitFail=true
+                                fi
+                        else
+                            passed=$((passed+1))
                         fi
                 fi
         fi
 done
-if $cross || $runOnly || $short || $testReg ; then
-        exit 0
+
+if $short || $testReg ; then
+  if [ "$exitFail" = true ] ; then
+    echo "ok: $passed, failed: $failed"
+    exit 1
+  else
+    echo "ok: $passed, failed: $failed"
+    exit 0
+  fi
 fi
-#mmake clean >/dev/null
-cd "$src/benchmark/tests"
-for f in *.sml; do
-        f=`basename "$f" .sml`
-        tmpf="/tmp/$f.$$"
-        case "$f" in
-        fxp|hamlet)
-                echo "skipping $f"
-        ;;
-        *)
-                echo "testing $f"
-                echo "val _ = Main.doit 0" | cat "$f.sml" - > "$tmpf.sml"
-                $mlton -output "$tmpf" "${flags[@]}"            \
-                        -default-ann 'nonexhaustiveMatch ignore'\
-                        -default-ann 'redundantMatch ignore'    \
-                        "$tmpf.sml"
-                if [ $? -ne 0 ]; then
-                        compFail "$f"
-                fi
-                rm -f "$tmpf" "$tmpf.sml"
-        ;;
-        esac
-done 
-#mmake clean >/dev/null
-cd "$src"
-for f in mllex mlyacc mlprof; do
-    tmpf="/tmp/$f.$$"
-    cd "$src/$f"
-    echo "testing $f"
-    mmake -W "$f" >/dev/null
-    "$mlton" "${flags[@]}" -output "$tmpf" "$f.mlb"
-    if [ $? -ne 0 ]; then
-        compFail "$f"
-    fi
-    rm -f "$tmpf"
-done
+
+#"$src/bin/mmake" clean >/dev/null
+#cd "$src/benchmark/tests"
+#for f in *.sml; do
+#        f=`basename "$f" .sml`
+#        tmpf="/tmp/$f.$$"
+#        case "$f" in
+#        fxp)
+#                echo "skipping $f"
+#        ;;
+#        *)
+#                echo "testing $f"
+#                echo "val _ = Main.doit 0" | cat "$f.sml" - > "$tmpf.sml"
+#                $mlton -output "$tmpf" "${flags[@]}"            \
+#                        -default-ann 'nonexhaustiveBind ignore'\
+#                        -default-ann 'nonexhaustiveMatch ignore'\
+#                        -default-ann 'redundantBind ignore'    \
+#                        -default-ann 'redundantMatch ignore'    \
+#                        "$tmpf.sml"
+#                if [ $? -ne 0 ]; then
+#                        compFail "$f"
+#                        exitFail=true
+#                fi
+#                rm -f "$tmpf" "$tmpf.sml"
+#        ;;
+#        esac
+#done
+#"$src/bin/mmake" clean >/dev/null
+#cd "$src"
+#for f in mllex mlyacc mlprof; do
+#    tmpf="/tmp/$f.$$"
+#    cd "$src/$f"
+#    echo "testing $f"
+#    "$src/bin/mmake" -W "$f" >/dev/null
+#    "$mlton" "${flags[@]}" -output "$tmpf" "$f.mlb"
+#    if [ $? -ne 0 ]; then
+#        compFail "$f"
+#        exitFail=true
+#    fi
+#    rm -f "$tmpf"
+#done
 
 rm -f "$tmp"
+
+if [ "$exitFail" = true ] ; then
+  echo "ok: $passed, failed: $failed"
+  exit 1
+else
+  echo "ok: $passed, failed: $failed"
+  exit 0
+fi
+
